aboutme/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.aboutme)
]

comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [

]

personalblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='homepage'),
    path('aboutme/', include('aboutme.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
    path('comments/', include('comments.urls', namespace='comments')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('<slug:slug>/comment/', views.add_comment, name='add_comment'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout')
]

aboutme/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=50)
    birth = models.DateField()
    slug = models.SlugField()
    
    def __str__(self):
        return self.name

class Pet(models.Model):
    name = models.CharField(max_length=30)
    breed = models.CharField(max_length=20)
    owner = models.ForeignKey(Person, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Post

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Comment by {self.author.username} on {self.post.title}, {self.created_at}"

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    image = models.ImageField(default='def_post.png', blank=True)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    content = models.TextField()
    slug = models.SlugField(unique=True)
    date_published = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write what are you thinking...', "class": "w-3/5 dark:bg-[#575757] mb-[10px] p-2 rounded-[4px] bg-[#d1d1d1] dark:text-white text-[#343434] focus:outline-none resize-none overflow-y-auto"}),
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput(attrs={
            "class": "dark:bg-[#696969] mb-[10px] w-64 p-2 rounded-lg bg-[#d1d1d1] dark:text-white text-[#343434] focus:outline-none"
        })
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={
            "class": "dark:bg-[#696969] mb-[10px] w-64 p-2 rounded-lg bg-[#d1d1d1] dark:text-white text-[#343434] focus:outline-none"
        })
    )
    password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(attrs={
            "class": "dark:bg-[#696969] mb-[10px] w-64 p-2 rounded-lg bg-[#d1d1d1] dark:text-white text-[#343434] focus:outline-none"
        })
    )

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "dark:bg-[#696969] mb-[10px] w-64 p-2 rounded-lg bg-[#d1d1d1] dark:text-white text-[#343434] focus:outline-none"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "dark:bg-[#696969] mb-[10px] w-64 p-2 rounded-lg bg-[#d1d1d1] dark:text-white text-[#343434] focus:outline-none"
    }))

aboutme/views.py
from django.shortcuts import render

def aboutme(request):
    return render(request, 'aboutme/aboutme.html')

comments/views.py
from django.shortcuts import render

personalblog/views.py
from django.shortcuts import render
from aboutme.models import Person

def homepage(request):
    person_list = Person.objects.all()
    return render(request, 'home.html', {'persons': person_list})

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from comments.forms import CommentForm
from django.contrib.auth.decorators import login_required

def post_list(request):
    posts = Post.objects.all().order_by('-date_published')
    return render(request, 'posts/posts.html', {'posts': posts})

def post_detail(request, slug):
    post = Post.objects.get(slug=slug)
    comments = post.comments.all().order_by('-created_at')
    form = CommentForm()
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'comments': comments,
        'form': form,
    })

@login_required(login_url='users:login')
def add_comment(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
    return redirect('posts:post_detail', slug=post.slug)

users/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login, logout

def profile(request):
    return render(request, 'users/profile.html')

def register_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('homepage')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('homepage')
    else:
        form = CustomAuthenticationForm()
    return render(request, "users/login.html", { "form": form })

def logout_user(request):
    logout(request)
    return redirect('homepage')

aboutme/templates/aboutme/aboutme.html
{% extends "base.html" %}
{% load static %}
{% block title %}
About me
{% endblock %}
{% block content %}
<div class="bg-[#d1d1d1] flex flex-col items-center mx-auto max-w-[90%] py-[15px] rounded-[10px] dark:bg-[#2a2a2a]">
    <h1 class="text-[50px] text-[#343434] m-0 dark:text-[#e5e5e5]">About me</h1>
</div>

<div class="max-w-[90%] mx-auto m-[40px]">
    <section class="bg-white rounded-[10px] p-[30px] shadow dark:bg-[#2a2a2a]">
        <div class="flex flex-col lg:flex-row items-center gap-[30px]">
            <img src="{% static 'images/autor.jpg' %}" alt="Author photo"
                class="w-[220px] h-[220px] object-cover rounded-full shadow-md">

            <div>
                <h2 class="text-[1.8rem] font-semibold text-[#343434] mb-[15px] dark:text-[#e5e5e5]">Hey there! 👋</h2>
                <p class="text-[#555] leading-relaxed text-justify mb-[15px] dark:text-[#cfcfcf]">
                    My name is Laura, and I’m someone who’s always been fascinated by how technology and creativity can
                    come together to build amazing things.
                    Ever since I was a kid, I loved taking things apart just to understand how they worked — whether it
                    was a computer, a camera, or even a toy car.
                    That curiosity slowly evolved into a genuine passion for web development and digital design, which
                    is what inspired me to create this personal blog.
                </p>

                <p class="text-[#555] leading-relaxed text-justify mb-[15px] dark:text-[#cfcfcf]">
                    I studied topics related to computer science and digital communication, and I enjoy sharing what I
                    learn along the way.
                    Here you’ll find posts about technology, lifestyle, and the small things that make everyday life
                    special.
                    I truly believe that learning is a continuous process, and that every new project, no matter how
                    small, is an opportunity to grow and improve.
                </p>

                <p class="text-[#555] leading-relaxed text-justify dark:text-[#cfcfcf]">
                    When I’m not writing or coding, I love exploring nature, spending time with animals, and cooking for
                    friends and family.
                    Photography is another one of my passions — I enjoy capturing quiet moments, places I’ve visited,
                    and spontaneous smiles that tell a story.
                    My goal with this blog is to build a little corner on the internet where I can share knowledge,
                    experiences, and inspiration with people like you.
                    Thanks for stopping by, and I hope you enjoy reading as much as I enjoy creating! 💛
                </p>
            </div>
        </div>
    </section>

    <section class="mt-[40px] grid sm:grid-cols-2 lg:grid-cols-3 gap-[20px]">
        <div class="bg-white rounded-[10px] p-[10px] shadow dark:bg-[#2a2a2a]">
            <img src="{% static 'images/about1.jpg' %}" alt="Gallery photo 1"
                class="rounded-[8px] w-full h-[250px] object-cover">
        </div>

        <div class="bg-white rounded-[10px] p-[10px] shadow dark:bg-[#2a2a2a]">
            <img src="{% static 'images/about2.jpg' %}" alt="Gallery photo 2"
                class="rounded-[8px] w-full h-[250px] object-cover">
        </div>

        <div class="bg-white rounded-[10px] p-[10px] shadow dark:bg-[#2a2a2a]">
            <img src="{% static 'images/about3.jpg' %}" alt="Gallery photo 3"
                class="rounded-[8px] w-full h-[250px] object-cover">
        </div>
    </section>
</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
<!-- POST_LIST SECTION -->
<div class="max-w-[90%] mx-auto m-[40px]">
    <section class="bg-white rounded-[10px] p-[30px] shadow dark:bg-[#2a2a2a]">
        <div class="flex flex-col lg:flex-row items-center gap-[30px]">
            <img src="{{ post.image.url }}" alt="{{ post.title }}"
                class="w-[220px] h-[220px] object-cover rounded-full shadow-md">
            <div>
                <h2 class="text-[1.8rem] font-semibold text-[#343434] mb-[5px] dark:text-[#e5e5e5]">
                    {{ post.title }}
                </h2>
                <p class="text-[#343434] leading-relaxed text-justify mb-[15px] dark:text-[#cfcfcf]">
                    Slug: {{ post.slug }}
                </p>
                <p class="text-[#343434] leading-relaxed text-justify mb-[15px] dark:text-[#cfcfcf]">
                    Posted {{ post.date_published|date:"d M Y" }}</p>
                <p class="text-[#555] leading-relaxed text-justify mb-[15px] dark:text-[#cfcfcf]">
                    {{ post.content|linebreaks }}
                </p>
            </div>
        </div>
    </section>
</div>

<!-- COMMENT SECTION -->
<div class="max-w-[90%] mx-auto m-[40px]">
    <div class="bg-[#d1d1d1] flex flex-col items-center py-[15px] rounded-[10px] dark:bg-[#2a2a2a] mb-[30px]">
        <h1 class="text-[20px] text-[#343434] m-0 dark:text-[#e5e5e5] font-semibold">Comments ({{ comments.count }})
        </h1>
    </div>
    {% if user.is_authenticated %}
    <form action="{% url 'posts:add_comment' post.slug %}" method="post">
        {% csrf_token %}

        {% for field in form %}
        <div class="w-full text-center">
            {{ field }}
        </div>
        {% endfor %}

        <div class="text-center">
            <button type="submit"
                class="cursor-pointer bg-[#343434] text-white rounded-[4px] px-[25px] py-[5px] no-underline hover:bg-[#575757] dark:hover:bg-[#696969] dark:bg-[#575757] dark:text-white">Post
                comment
            </button>
        </div>
    </form>
    {% else %}
    <p class="text-center mt-4">
        <a href="{% url 'users:login' %}?next={{ request.path }}" class="w-2/5 bg-[#343434] text-white rounded-[4px] px-[25px] py-[10px] mt-[20px] self-start no-underline hover:bg-[#575757] dark:hover:bg-[#696969] dark:bg-[#575757] dark:text-white cursor-pointer">
            Log in to comment
        </a>
    </p>
    {% endif %}

    {% for comment in comments %}

    <section class="mt-[20px] rounded-[10px] p-[10px] shadow dark:bg-[#2a2a2a]">
        <div class="flex flex-col lg:flex-row items-center gap-[30px] px-[20px] py-[10px]">
            <img src="{% static 'images/default_user.jpg' %}" alt="user profile photo"
                class="w-[50px] h-[50px] object-cover rounded-full shadow-md">
            <div>
                <div class="text-[#343434] font-semibold text-justify dark:text-[#cfcfcf] text-[20px]">
                    {{ comment.author.username }}</div>
                <div class="text-[#343434] leading-relaxed text-justify mb-[15px] dark:text-[#cfcfcf]">
                    Published {{ comment.created_at|date:"d M Y" }}, {{ comment.created_at|time:"H:i" }}</div>
                <div class="text-[#555] leading-relaxed text-justify dark:text-[#cfcfcf]">
                    {{ comment.text|linebreaks }}
                </div>
            </div>
        </div>
    </section>

    {% empty %}
    <p class="mt-[30px] text-[25px] text-[#343434] font-bold m-0 dark:text-[#e5e5e5] text-center">No comments yet. Be
        the first!</p>

    {% endfor %}
</div>
{% endblock %}

posts/templates/posts/posts.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Posts
{% endblock %}

{% block content %}
<div class="bg-[#d1d1d1] flex flex-col items-center mx-auto max-w-[90%] py-[15px] rounded-[10px] dark:bg-[#2a2a2a]">
    <h1 class="text-[50px] text-[#343434] m-0 dark:text-[#e5e5e5]">Posts</h1>
</div>

<div class="max-w-[90%] mx-auto m-[40px]">
    <section class="flex flex-col gap-[20px]">
        {% for post in posts %}
        <article class="flex gap-[15px] bg-white p-[15px] rounded-[10px] shadow dark:bg-[#2a2a2a]">
            <img src="{{ post.image.url }}" alt="Post image" class="w-[150px] h-[150px] object-cover rounded-[8px]">
            <div class="flex flex-col">
                <h2 class="text-[1.2rem] font-semibold m-0 dark:text-[#e5e5e5]">{{ post.title }}</h2>
                <p class="mb-[10px] text-[#555] dark:text-[#cfcfcf]">{{ post.description }}</p>
                <a href="{% url 'posts:post_detail' slug=post.slug %}"
                    class="bg-[#343434] text-white rounded-[4px] px-[15px] py-[5px] mt-auto self-start no-underline hover:bg-[#575757] dark:hover:bg-[#696969] dark:bg-[#575757] dark:text-white">
                    Read more
                </a>
            </div>
        </article>
        {% empty %}
        <p class="text-[25px] text-[#343434] font-bold m-0 dark:text-[#e5e5e5] text-center">No posts yet.</p>
        {% endfor %}
    </section>
</div>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="font-[Montserrat,Arial,Calibri]">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<script src="{% static 'js/theme_toggle.js' %}" defer></script>-->
    <title>{% block title %}My Personal Blog{% endblock %}</title>
    {% tailwind_css %}
    {% load static %}
</head>

<body
    class="min-h-screen flex flex-col font-[Montserrat,Arial,Calibri] bg-[#f0f0f0] m-0 dark:bg-[#0f0f0f] dark:text-[#e5e5e5]">

    <header class="h-[85px]">
        <div class="flex items-center justify-between px-[50px] h-full bg-[#f0f0f0] dark:bg-[#0f0f0f]">
            <div class="text-[25px] font-bold text-[#343434] dark:text-[#e5e5e5]">My Personal Blog</div>
            <nav>
                <ul class="flex gap-[50px] list-none">
                    <li><a href="/"
                            class="text-[#343434] hover:text-[#575757] no-underline dark:text-[#e5e5e5] dark:hover:text-[#f3f3f3]">Home</a>
                    </li>
                    <li><a href="/aboutme"
                            class="text-[#343434] hover:text-[#575757] no-underline dark:text-[#e5e5e5] dark:hover:text-[#f3f3f3]">About
                            me</a></li>
                    <li><a href="/posts"
                            class="text-[#343434] hover:text-[#575757] no-underline dark:text-[#e5e5e5] dark:hover:text-[#f3f3f3]">Posts</a>
                    </li>
                    <li><a href=""
                            class="text-[#343434] hover:text-[#575757] no-underline dark:text-[#e5e5e5] dark:hover:text-[#f3f3f3]">Contact</a>
                    </li>
                    <li class="relative group">
                        <img src="{% static 'images/default_user.jpg' %}" alt="Perfil"
                            class="w-8 h-8 rounded-full cursor-pointer border border-gray-300 dark:border-gray-600 object-cover" />

                        <ul class="absolute right-0 w-40 bg-white dark:bg-[#1c1c1c] border border-gray-200 dark:border-gray-700
                        rounded-lg shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible">
                            {% if user.is_authenticated %}
                            <li>
                                <a href="{% url 'users:profile' %}"
                                    class="block px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-[#2a2a2a]">Profile</a>
                            </li>
                            <li>
                                <a href="{% url 'users:logout' %}"
                                    class="block px-4 py-2 text-sm text-[#D5534E] dark:text-[#D5534E] hover:bg-gray-100 dark:hover:bg-[#2a2a2a]">Log
                                    out</a>
                            </li>
                            {% else %}
                            <li>
                                <a href="{% url 'users:login' %}"
                                    class="block px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-[#2a2a2a]">Log
                                    in</a>
                            </li>
                            <li>
                                <a href="{% url 'users:register' %}"
                                    class="block px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-[#2a2a2a]">Sign
                                    up</a>
                            </li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <main class="flex-grow">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="text-white bg-[#343434] text-center text-[15px] py-[25px] mb-0 dark:bg-[#0b0b0b]">
        Made by ♥Laura
    </footer>

    <!--<button id="theme-toggle"
        class="fixed bottom-5 right-5 p-3 rounded-full shadow-md bg-[#e5e5e5] dark:bg-[#2b2b2b] text-[#343434] dark:text-[#f3f3f3] cursor-pointer z-50">
        🌞
    </button>-->
</body>

</html>

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Log in
{% endblock %}
{% block content %}

<div class="max-w-[30%] mx-auto m-[40px]">
    <section class="flex flex-col text-center bg-white p-[15px] rounded-[10px] shadow dark:bg-[#2a2a2a]">
        <h1 class="text-[1.8rem] font-semibold text-[#343434] mb-[10px] dark:text-[#e5e5e5] shadow-md py-[10px]">Log in
            to your account</h1>
        <form class='text-center' action="{% url 'users:login' %}" method='post'>
            {% csrf_token %}

            {% for field in form %}
            <div class="w-full text-center">
                <label class="block mb-[5px] mt-4 text-[#343434] font-[20px] font-semibold dark:text-[#e5e5e5]">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                <p class="text-red-400 text-sm mt-1">{{ field.errors|striptags }}</p>
                {% endif %}
            </div>
            {% endfor %}

            {% if request.GET.next %}
            <input type='hidden' name='next' value='{{ request.GET.next }}'>
            {% endif %}

            <button type="submit"
                class="w-full bg-[#343434] text-white rounded-[4px] px-[15px] py-[5px] mt-[20px] self-start no-underline hover:bg-[#575757] dark:hover:bg-[#696969] dark:bg-[#575757] dark:text-white cursor-pointer">Log
            in</button>
        </form>
    </section>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}
About me
{% endblock %}
{% block content %}
<div class="bg-[#d1d1d1] flex flex-col items-center mx-auto max-w-[90%] py-[15px] rounded-[10px] dark:bg-[#2a2a2a]">
    <h1 class="text-[50px] text-[#343434] m-0 dark:text-[#e5e5e5]">Profile</h1>
</div>

<div class="max-w-[90%] mx-auto m-[40px]">
    <section class="bg-white rounded-[10px] p-[30px] shadow dark:bg-[#2a2a2a]">
        <div class="flex flex-col lg:flex-row items-center gap-[30px]">
            <img src="{% static 'images/autor.jpg' %}" alt="User photo"
                class="w-[220px] h-[220px] object-cover rounded-full shadow-md">

            <div>
                <div class="">
                    <h2 class="text-[1.8rem] font-semibold text-[#343434] mb-[15px] dark:text-[#e5e5e5]">{{ user.username }}</h2>
                    <a href=""
                        class="bg-[#343434] text-white rounded-[4px] px-[15px] py-[5px] mt-auto self-start no-underline hover:bg-[#575757] dark:hover:bg-[#696969] dark:bg-[#575757] dark:text-white">
                        Edit profile
                    </a>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Sign up
{% endblock %}
{% block content %}

<div class="max-w-[30%] mx-auto m-[40px]">
    <section class="flex flex-col text-center bg-white p-[15px] rounded-[10px] shadow dark:bg-[#2a2a2a]">
        <h1 class="text-[1.8rem] font-semibold text-[#343434] mb-[10px] dark:text-[#e5e5e5] shadow-md py-[10px]">Create an account</h1>
        <form class='text-center' action="{% url 'users:register' %}" method='post'>
            {% csrf_token %}
            
            {% for field in form %}
            <div class="w-full text-center">
                <label class="block mb-[5px] mt-4 text-[#343434] font-[20px] font-semibold dark:text-[#e5e5e5]">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                <p class="text-red-400 text-sm mt-1">{{ field.errors|striptags }}</p>
                {% endif %}
            </div>
            {% endfor %}

            <button type=”submit”
                class="w-full bg-[#343434] text-white rounded-[4px] px-[15px] py-[5px] mt-[20px] self-start no-underline hover:bg-[#575757] dark:hover:bg-[#696969] dark:bg-[#575757] dark:text-white cursor-pointer">Create account</button>
        </form>
    </section>
</div>

{% endblock %}